management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring
    description: Project for an interview.
    author: Gustavo Lyra
    version: '@project.version@'
spring:
  profiles:
    active: dev